C make files
oss-slu/PilotDataSynchronization pull request #33
Opened 2024-10-20 05:08 UTC by carlyrhoover

### Fixes #29 

---

### **What was changed?**
-CMakeLists.txt was modified. Include files were edited in plugin. 
---

### **Why was it changed?**

Platform was not able to be defined, so it was specified in the CmakeLists.txt. Header file was also not being properly included, so it was removed to avoid that error. The project builds properly, but is unable to be tested due to the nature of the plugin itself, which is an issue to be addressed in the future. 

---

### **How was it changed?**

No major changes. Includes in the plugin file were deleted, and CMakeLists.txt was edited.

2024-10-21 21:31 UTC, harshitha-thota commented
Suggested Improvements:
Comment out the test stuff from CMakeLists.txt(don’t remove, just comment out).

Please address the above suggested improvement. After testing, I’ll merge the PR if everything works as expected. I look forward to seeing your updates!

2024-10-24 13:56 UTC, kate-holdener requested changes
@carlyrhoover please address the requested changes.

2024-10-24 13:56 UTC, kate-holdener commented on src/hello-world.cpp
Remove this from the PR, I added this file just to see if we can build it with cmake.

2024-10-24 13:56 UTC, kate-holdener commented on CMakeLists.txt
> +gtest_discover_tests(plugin_tests)
Comment out this part, since it doesn't quite work with the plugin_test.cpp yet.

2024-10-27 23:31 UTC, carlyrhoover commented
The branch is now updated with the testing code in the CMakeFiles commented out!

2024-10-30 14:37 UTC, harshitha-thota approved these changes

2024-10-30 15:22 UTC, merged